### ISSUE TITLE
"crash" when using jar files (uncompressed and deflated ones); endless folder structure in release zip

### ISSUE THREAD

**Issue by ardera** [Team-CC-Corp/JVML-JIT#70]
When you use a compressed jar file (deflated), the ziplib crashes (294: attempt to get length of nil).
If you use an uncompressed jar file like the cc_rt jar, the screen turns black after a few seconds.

Also, the 0.5.1 jvml.zip.base64 is broken, it contains an endless chain of "asm/build/"; my windows explorer crashed while trying to delete it. (I got it deleted using CraftOS)

**Comment by ElvishJerricco** [comment]
I've fixed the asm/build/ recursive thing.

But I can't reproduce your issues with jar files. Deflated and uncompressed files work fine for me.

**Comment by Yevano** [comment]
That's weird. First of all, I'm pretty sure compressed jars are unsupported for now, so sorry about that. I've seen the the zip library do something like what you describe before, but found that after trying again it was working.

And about the zip file having an endless chain, I have no idea. I guess @ElvishJerricco might know something about that since he does the releases. If you want to use JVML in the mean time, I suggest cloning the repository directly and compiling from there.

**Comment by ardera** [comment]
Mhh that's odd. A friend said jars were buggy for him too.

**Comment by ElvishJerricco** [comment]
If you can provide a method to produce a zip that doesn't work, we can more easily debug this.

**Comment by ElvishJerricco** [comment]
Closed for lack of reproducibility.
